defaults: &defaults
  adapter: mysql2
  pool: 5
  username: hoyamada
  password: orih6254
  socket: /tmp/mysql.sock

development:
  <<: *defaults
  database: device_development

test:
  <<: *defaults
  database: device_test

production:
  <<: *defaults
  host: production_db_host
  database: device_production
